name: ReDoc for OpenAPI UI
type: module
description: Provides display of OpenAPI docs using the ReDoc library.
core_version_requirement: '^8 || ^9'
package: OpenAPI
dependencies:
  - openapi_ui:openapi_ui
